version: '3.8'

services:
    frontend:
      build:
        context: ./frontend
      ports:
        - "3000:3000"
      enviroment:
        NEXT_PUBLIC_API_URL: http://localhost:5000
      volumes:
        - ./frontend:/app
      depends_on:
        - backend
    backend:
      build:
        context: ./backend
      ports:
        - "5000:5000"
      enviroment:
        - NODE_ENV=development
      volumes:
        - ./backend:/usr/src/app